name: CI/CD Pipeline

on:
  push:
    branches:
      - ['*']
  pull_request:
    branches:
      - [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
        
      - name: Run Tests
        run: |
          pip install pytest
          pytest tests/*.py